### ISSUE TITLE
Library 1

### ISSUE THREAD

**Issue by kiennt** [ElixirVietnam/elixir-school#28]
https://elixirschool.com/lessons/libraries/guardian/

**Comment by nguyenduyhao1111** [comment]
self-assigned

**Comment by kiennt** [comment]
Thanks @nguyenduyhao1111 💯

**Comment by kiennt** [comment]
@nguyenduyhao1111 any process on this issue em?

**Comment by nguyenduyhao1111** [comment]
@kiennt e mới tạo xong PR á anh.

**Comment by nguyenduyhao1111** [comment]
dạ thank anh @kiennt đã review. e fix các comment rồi ạ.
